### ISSUE TITLE
Ability to add table prefix

### ISSUE THREAD

**Issue by szogi1910** [Franc1sco/MostActive#4]
Hello
Is it possible to have a function that will give you the ability to set a table prefix,
online_dd2
online_4fun
e.t.c

**Comment by shanapu** [comment]
So server operators can use different tables/statistics for various servers?

We could add a cvar to define the table name, so operators can prefix them for each server.
So we also need a variable for tables in webservers config.

Spontaneous, out of my head, I don't have a good idea how to solve the web part, to suit single & multiple database tables.

**Comment by szogi1910** [comment]
> So server operators can use different tables/statistics for various servers?

For a given moment the table name is defined rigidly so that another prefix for two different servers cannot be specified.So to make statistics for several servers you need to create separate databases for them
