### ISSUE TITLE
No records on the page

### ISSUE THREAD

**Issue by szogi1910** [Franc1sco/MostActive#5]
welcome back
After uploading the web version and configuring it in the config.php file on the site there is no information

Fatal error: Call to undefined method DateTime::diff() in /home/pggames/domains/project-games.eu/public_html/statystyki/online/dd2/inc/function.php on line 115

**Comment by szogi1910** [comment]
Fatal error: Call to undefined method DateTime::diff() in /home/pggames/domains/project-games.eu/public_html/statystyki/online/dd2/inc/function.php on line 115

**Comment by shanapu** [comment]
Did you solve this issue?
Would you be so kind and let us know what was the reason & solution for your issue?
So when other people run into the same issue, they will find help here?

**Comment by szogi1910** [comment]
Yes, I solved the problem
I used php version 5.1 for a directory after changing to 5.3 problem solved
