### ISSUE TITLE
Reason for str_replace of < to &lt;

### ISSUE THREAD

**Issue by BrutalCSkakan** [Franc1sco/MostActive#6]
Hello there!
What's the reason for these rows? 
$name = str_replace("{", "", $row['playername']);
$name = str_replace("}", "", $name);
$name = str_replace("<", "&lt;", $name);
$name = str_replace("&", "&amp;", $name);

Is this some type of security for possible SQL injections, or is this just because of some type of unicode fix? 
I've done alot of modifications and these rows currently don't need to be applied to my project, but I don't want to remove them before someone tells me that it's safe.

**Comment by shanapu** [comment]
This is a leftover from an older project. IIRC it's only a beauty fix. You can remove it.
Was taken over from the stamm webinterface.

The security for possible SQL injections is in here: https://github.com/Franc1sco/MostActive/blob/master/webserver/index.php#L133
be sure you use `escape($string)` or `mysqli_real_escape_string($link, $string);` after every user input (e.g. search formular)

**Comment by BrutalCSkakan** [comment]
Ah awesome, thanks!
